spring:
  datasource:
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/account_book?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.hetian.account.domain
  mapper-locations: classpath:mybatis\mapper\*.xml


